<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AdminNotificationController;
use App\Http\Controllers\Api\V1\AuctionApiController;
use App\Http\Controllers\Api\V1\PaymentApiController;
use App\Http\Controllers\Api\V1\SupportApiController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BidPreauthController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\PortalController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\UserAuctionController;
use App\Http\Controllers\UserDashboardController;
use App\Http\Controllers\WalletController;
use Illuminate\Support\Facades\Route;

Route::get('/', [PortalController::class, 'home'])->name('home');
Route::get('/login', [AuthController::class, 'showLogin'])->name('login');
Route::post('/login', [AuthController::class, 'login'])->name('login.submit');
Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
Route::get('/forgot-password', [PasswordController::class, 'forgot'])->name('password.forgot');
Route::post('/forgot-password/send-otp', [PasswordController::class, 'sendOtp'])->name('password.forgot.send-otp');
Route::post('/forgot-password/verify-otp', [PasswordController::class, 'verifyOtp'])->name('password.forgot.verify-otp');
Route::get('/reset-password/{token}', [PasswordController::class, 'showResetForm'])->name('password.reset.form');
Route::post('/reset-password/{token}', [PasswordController::class, 'updatePassword'])->name('password.reset.submit');
Route::get('/register', [RegistrationController::class, 'show'])->name('register');
Route::post('/register', [RegistrationController::class, 'submit'])->name('register.submit');
Route::post('/register/send-email-otp', [RegistrationController::class, 'sendEmailOtp'])->name('register.otp.email.send');
Route::post('/register/verify-email-otp', [RegistrationController::class, 'verifyEmailOtp'])->name('register.otp.email.verify');
Route::post('/register/send-mobile-otp', [RegistrationController::class, 'sendMobileOtp'])->name('register.otp.mobile.send');
Route::post('/register/verify-mobile-otp', [RegistrationController::class, 'verifyMobileOtp'])->name('register.otp.mobile.verify');
Route::post('/register/verify-pan', [RegistrationController::class, 'verifyPan'])->name('register.pan.verify');
Route::post('/register/check-pan-status', [RegistrationController::class, 'checkPanStatus'])->name('register.pan.status');
Route::get('/payments/registration/initiate', [PaymentController::class, 'initiateRegistrationPayment'])->name('payments.registration.initiate');
Route::get('/payments/registration/retry', [PaymentController::class, 'initiateRegistrationPayment'])->name('payments.registration.retry');
Route::match(['get', 'post'], '/payu/auction/success', [PaymentController::class, 'auctionSuccess'])->name('payu.auction.success');
Route::match(['get', 'post'], '/payu/auction/failure', [PaymentController::class, 'auctionFailure'])->name('payu.auction.failure');
Route::match(['get', 'post'], '/payu/registration/success', [PaymentController::class, 'registrationSuccess'])->name('payu.registration.success');
Route::match(['get', 'post'], '/payu/registration/failure', [PaymentController::class, 'registrationFailure'])->name('payu.registration.failure');
Route::match(['get', 'post'], '/payu/bid-preauth/success', [BidPreauthController::class, 'success'])->name('payu.bid-preauth.success');
Route::match(['get', 'post'], '/payu/bid-preauth/failure', [BidPreauthController::class, 'failure'])->name('payu.bid-preauth.failure');
// [EMD/WALLET DISABLED] Route::match(['get', 'post'], '/payu/wallet/success', [PaymentController::class, 'walletSuccess'])->name('payu.wallet.success');
// [EMD/WALLET DISABLED] Route::match(['get', 'post'], '/payu/wallet/failure', [PaymentController::class, 'walletFailure'])->name('payu.wallet.failure');

Route::middleware('session.auth')->group(function (): void {
    Route::get('/user/auctions', [UserAuctionController::class, 'index'])->name('user.auctions.index');
    Route::get('/user/dashboard', [UserDashboardController::class, 'index'])->name('user.dashboard');
    Route::get('/user/auctions/{auctionId}', [UserAuctionController::class, 'show'])->name('user.auctions.show');
    Route::post('/user/auctions/{auctionId}/join', [UserAuctionController::class, 'joinAuction'])->name('user.auctions.join');
    Route::post('/user/auctions/{auctionId}/watch', [UserAuctionController::class, 'toggleWatchlist'])->name('user.auctions.watch');
    Route::post('/user/auctions/{auctionId}/bid', [UserAuctionController::class, 'placeBid'])->name('user.auctions.bid');
    Route::get('/user/auctions/{auctionId}/status', [UserAuctionController::class, 'auctionStatus'])->name('user.auctions.status');
    // [EMD DISABLED] Route::post('/user/auctions/{auctionId}/complete-payment', [UserAuctionController::class, 'completePayment'])->name('user.auctions.complete-payment');
    // [EMD DISABLED] Route::post('/user/auctions/{auctionId}/release-emd', [UserAuctionController::class, 'releaseEmd'])->name('user.auctions.release-emd');
    Route::get('/user/my-bids', [UserAuctionController::class, 'myBids'])->name('user.my-bids');
    Route::get('/user/profile', [UserAuctionController::class, 'profile'])->name('user.profile');
    Route::post('/user/profile/password/send-otp', [UserAuctionController::class, 'profilePasswordSendOtp'])->name('user.profile.password.send-otp');
    Route::post('/user/profile/password/update', [UserAuctionController::class, 'profilePasswordUpdate'])->name('user.profile.password.update');
    Route::post('/user/profile/email/send-otp', [UserAuctionController::class, 'profileEmailSendOtp'])->name('user.profile.email.send-otp');
    Route::post('/user/profile/email/update', [UserAuctionController::class, 'profileEmailUpdate'])->name('user.profile.email.update');
    Route::post('/user/profile/mobile/send-otp', [UserAuctionController::class, 'profileMobileSendOtp'])->name('user.profile.mobile.send-otp');
    Route::post('/user/profile/mobile/update', [UserAuctionController::class, 'profileMobileUpdate'])->name('user.profile.mobile.update');
    Route::get('/user/notifications', [UserAuctionController::class, 'notifications'])->name('user.notifications');
    Route::get('/user/notifications/new', [UserAuctionController::class, 'notificationComposeForm'])->name('user.notifications.new');
    Route::get('/user/notifications/{id}', [UserAuctionController::class, 'notificationShow'])->whereNumber('id')->name('user.notifications.show');
    Route::match(['get', 'post'], '/user/support', function () {
        return redirect()->route('user.notifications.new', [], 302);
    })->name('user.support');
    Route::post('/user/notifications/compose', [UserAuctionController::class, 'composeAdminMessage'])->name('user.notifications.compose');
    Route::post('/user/notifications/{id}/reply', [UserAuctionController::class, 'replyToAdminMessage'])->name('user.notifications.reply');
    // [EMD/WALLET DISABLED] Route::get('/wallet', [WalletController::class, 'index'])->name('wallet.index');
    // [EMD/WALLET DISABLED] Route::get('/wallet/export', [WalletController::class, 'export'])->name('wallet.export');
    // [EMD/WALLET DISABLED] Route::post('/wallet/add-money', [PaymentController::class, 'initiateWalletTopup'])->name('wallet.add-money');
    // [EMD/WALLET DISABLED] Route::get('/wallet/balance', [WalletController::class, 'balance'])->name('wallet.balance');
    // [EMD/WALLET DISABLED] Route::get('/wallet/history', [WalletController::class, 'history'])->name('wallet.history');
    Route::get('/invoices/auction/{auctionId}', [InvoiceController::class, 'auction'])->name('invoices.auction');
    Route::get('/invoices/registration', [InvoiceController::class, 'registration'])->name('invoices.registration');
    Route::get('/payments/auction/{auctionId}/initiate', [PaymentController::class, 'initiateAuctionPayment'])->name('payments.auction.initiate');
    Route::get('/payments/auction/{auctionId}/participation/initiate', [PaymentController::class, 'initiateAuctionParticipationPayment'])->name('payments.auction.participation.initiate');

    // API v1 (session-authenticated)
    Route::get('/api/v1/auctions', [AuctionApiController::class, 'index'])->name('api.v1.auctions.index');
    Route::get('/api/v1/auctions/{id}', [AuctionApiController::class, 'show'])->name('api.v1.auctions.show');
    Route::post('/api/v1/auctions/{id}/bids', [AuctionApiController::class, 'placeBid'])->name('api.v1.auctions.bids.place');
    Route::get('/api/v1/notifications', [AuctionApiController::class, 'notifications'])->name('api.v1.notifications.index');
    Route::post('/api/v1/payments/auctions/{auctionId}/initiate', [PaymentApiController::class, 'initiateAuctionPayment'])->name('api.v1.payments.auction.initiate');
    Route::get('/api/v1/payments/transactions/{transactionId}', [PaymentApiController::class, 'transactionStatus'])->name('api.v1.payments.transactions.show');
    Route::get('/api/v1/support/tickets', [SupportApiController::class, 'index'])->name('api.v1.support.tickets.index');
    Route::post('/api/v1/support/tickets', [SupportApiController::class, 'store'])->name('api.v1.support.tickets.store');
});

Route::middleware('session.admin')->group(function (): void {
    Route::get('/admin/dashboard', [AdminController::class, 'dashboard'])->name('admin.dashboard');
    Route::get('/admin/operations', [AdminController::class, 'operations'])->name('admin.operations');
    Route::get('/admin/bids', [AdminController::class, 'bidsIndex'])->name('admin.bids.index');
    Route::get('/admin/notifications', [AdminNotificationController::class, 'index'])->name('admin.notifications');
    Route::post('/admin/notifications/send', [AdminNotificationController::class, 'send'])->name('admin.notifications.send');
    Route::get('/admin/notifications/{id}', [AdminNotificationController::class, 'showThread'])->name('admin.notifications.thread');
    Route::post('/admin/notifications/{id}/reply', [AdminNotificationController::class, 'reply'])->name('admin.notifications.reply');
    Route::get('/admin/auctions', [AdminController::class, 'auctionsIndex'])->name('admin.auctions.index');
    Route::match(['get', 'post'], '/admin/auctions/add', [AdminController::class, 'addAuction'])->name('admin.auctions.add');
    Route::match(['get', 'post'], '/admin/auctions/{id}/edit', [AdminController::class, 'editAuction'])->name('admin.auctions.edit');
    Route::get('/admin/auctions/{id}/delete', [AdminController::class, 'deleteAuction'])->name('admin.auctions.delete');
    Route::get('/admin/auctions/{id}/close', [AdminController::class, 'closeAuction'])->name('admin.auctions.close');
    Route::get('/admin/auctions/{id}/reopen', [AdminController::class, 'reopenAuction'])->name('admin.auctions.reopen');
    Route::get('/admin/auctions/{id}/cancel', [AdminController::class, 'cancelAuction'])->name('admin.auctions.cancel');
    Route::get('/admin/auctions/{id}/bids', [AdminController::class, 'viewBids'])->name('admin.auctions.bids');
    Route::match(['get', 'post'], '/admin/completed', [AdminController::class, 'completed'])->name('admin.completed');
    Route::match(['get', 'post'], '/admin/manage-users', [AdminController::class, 'manageUsers'])->name('admin.manage-users');
    Route::get('/admin/users/{id}', [AdminController::class, 'userDetails'])->name('admin.users.show');
    Route::post('/admin/users/{id}/toggle-block', [AdminController::class, 'toggleUserBlock'])->name('admin.users.toggle-block');
    Route::get('/admin/users/{id}/invoice/registration', [InvoiceController::class, 'adminRegistration'])->name('admin.invoices.registration');
    Route::get('/admin/users/{id}/invoice/auction/{auctionId}', [InvoiceController::class, 'adminAuction'])->name('admin.invoices.auction');
    Route::match(['get', 'post'], '/admin/settings', [AdminController::class, 'settings'])->name('admin.settings');
    Route::match(['get', 'post'], '/admin/upload-excel', [AdminController::class, 'uploadExcel'])->name('admin.upload-excel');
    Route::match(['get', 'post'], '/admin/support-tickets', [AdminController::class, 'supportTickets'])->name('admin.support.tickets');
    Route::get('/admin/blacklist', [AdminController::class, 'blacklist'])->name('admin.blacklist');
    Route::post('/admin/blacklist/{id}/toggle', [AdminController::class, 'toggleBlacklist'])->name('admin.blacklist.toggle');
    Route::get('/admin/audit-logs', [AdminController::class, 'auditLogs'])->name('admin.audit.logs');
});
